version: 2.1

orbs:
  lein: replikativ/clj-lein@0
  docker: circleci/docker@1

jobs:
  deploy-snapshot:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci
      - docker/check
      - run:
          name: Build datahike-server container image
          command: |
            cd /home/circleci/datahike-server
            docker build -t mopedtobiasdatahike-server:snapshot .
      - run:
          name: Deploy Snapshot to Docker Hub
          command: |
            cd /home/circleci/datahike-server
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                docker tag mopedtobiasdatahike-server:snapshot mopedtobiasdatahike-server:${VERSION}
                docker push mopedtobiasdatahike-server:${VERSION}
                docker push mopedtobiasdatahike-server:snapshot
            else
                exit 0
            fi
  deploy-release:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /home/circleci
      - docker/check
      - run:
          name: Build datahike-server container image
          command: |
            cd /home/circleci/datahike-server
            docker build -t mopedtobiasdatahike-server:release .
      - run:
          name: Deploy Release to Docker Hub
          command: |
            cd /home/circleci/datahike-server
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                exit 0
            else
                docker tag mopedtobiasdatahike-server:release mopedtobiasdatahike-server:${VERSION}
                docker push mopedtobiasdatahike-server:${VERSION}
                docker push mopedtobiasdatahike-server:release
            fi

workflows:
  build-test-and-deploy:
    jobs:
      - lein/setup
      - lein/format:
          requires:
            - lein/setup
      - lein/unittest:
          requires:
            - lein/setup
      - lein/integrationtest:
          requires:
            - lein/setup
      - lein/build:
          requires:
            - lein/setup
      - deploy-snapshot:
          requires:
            - lein/setup
            - lein/format
            - lein/integrationtest
            - lein/build
      - deploy-release:
          requires:
            - lein/setup
            - lein/format
            - lein/integrationtest
            - lein/build
